#! /bin/sh

echo "restoring computer dotfiles"
# stow zsh
stow zsh-new
# stow neovim
stow neovim-new
# stow alacritty
stow alacritty-new
#stow i3
#stow Xresources
# stow tmux
stow tmux-new
#stow compton
# stow vim
stow tmuxinator
# stow datagrip
stow asdf
stow fzf
stow spaceship
stow bashtop
stow ghostty
stow yazi
stow opencode
stow crush
echo "We are done restoring dotfiles!"

